### ISSUE TITLE
NoClassDefFoundError on recompile

### ISSUE THREAD

**Issue by PseudoKnight** [PseudoKnight/CHDiscord#7]
From Discord:

mur: Starting getting this when I /reloadalias, specifically CHDiscord is failing to start. It's up to date, and I've not touched any server config/plugins at all (or even restarted it since it was working last), it just started happening. Any ideas?
```
[14:30:56] [Server thread/INFO]: [CommandHelper] CHDiscord 2.5.0 loaded.
[14:30:57] [JDA RateLimit-Worker 1/ERROR]: [net.dv8tion.jda.internal.requests.RateLimiter] Encountered exception trying to execute request
java.lang.NoClassDefFoundError: Could not initialize class net.dv8tion.jda.api.utils.data.DataObject
    at net.dv8tion.jda.api.requests.Response.parseBody(Response.java:204) ~[?:?]
    at net.dv8tion.jda.api.requests.Response.parseBody(Response.java:182) ~[?:?]
    at net.dv8tion.jda.api.requests.Response.get(Response.java:124) ~[?:?]
    at net.dv8tion.jda.api.requests.Response.getObject(Response.java:105) ~[?:?]
    at net.dv8tion.jda.api.utils.SessionControllerAdapter.lambda$getGateway$0(SessionControllerAdapter.java:86) ~[?:?]
    at net.dv8tion.jda.internal.requests.RestActionImpl.handleSuccess(RestActionImpl.java:278) ~[?:?]
    at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:268) ~[?:?]
    at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259) ~[?:?]
    at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:237) ~[?:?]
    at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:141) ~[?:?]
    at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:124) ~[?:?]
    at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:478) ~[?:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:30:57] [Server thread/INFO]: [CommandHelper] [0;33;22m155 MethodScript files processed[m
```
All I can think of is I updated to Java 17 maybe a week ago, but it was working with that for a bit

**Comment by PseudoKnight** [comment]
I suspect it might be not shutting down properly. By testing discord_connect immediately following discord_broadcast, I was able to induce the following reproduceable error.
```
[07:20:08] [JDA RateLimit-Worker 1/ERROR]: [net.dv8tion.jda.internal.requests.Requester] There was an I/O error while executing a REST request: interrupted
[07:20:08] [ForkJoinPool.commonPool-worker-16/ERROR]: [net.dv8tion.jda.api.requests.RestAction] RestAction queue returned failure: [ErrorResponseException] -1: java.io.InterruptedIOException
java.io.InterruptedIOException: interrupted
	at libs.okio.Timeout.throwIfReached(Timeout.java:146) ~[?:?]
	at libs.okio.Okio$1.write(Okio.java:76) ~[?:?]
	at libs.okio.AsyncTimeout$1.write(AsyncTimeout.java:180) ~[?:?]
	at libs.okio.RealBufferedSink.flush(RealBufferedSink.java:224) ~[?:?]
	at libs.okhttp3.internal.http2.Http2Writer.flush(Http2Writer.java:121) ~[?:?]
	at libs.okhttp3.internal.http2.Http2Connection.flush(Http2Connection.java:407) ~[?:?]
	at libs.okhttp3.internal.http2.Http2Stream$FramingSink.close(Http2Stream.java:609) ~[?:?]
	at libs.okio.ForwardingSink.close(ForwardingSink.java:47) ~[?:?]
	at libs.okio.RealBufferedSink.close(RealBufferedSink.java:248) ~[?:?]
	at libs.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:84) ~[?:?]
	at libs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
	at libs.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[?:?]
	at libs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
	at libs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
	at libs.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[?:?]
	at libs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
	at libs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
	at libs.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[?:?]
	at libs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
	at libs.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) ~[?:?]
	at libs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
	at libs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
	at libs.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264) ~[?:?]
	at libs.okhttp3.RealCall.execute(RealCall.java:93) ~[?:?]
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:201) ~[?:?]
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:141) ~[?:?]
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:124) ~[?:?]
	at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:478) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.dv8tion.jda.api.exceptions.ContextException
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[?:?]
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71) ~[?:?]
	at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:197) ~[?:?]
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:573) ~[?:?]
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:539) ~[?:?]
	at me.pseudoknight.chdiscord.ChannelFunctions$discord_broadcast.exec(ChannelFunctions.java:56) ~[?:?]
	at com.laytonsmith.core.Script.eval(Script.java:462) ~[commandhelper-3.3.5-SNAPSHOT-full.jar:?]
	at com.laytonsmith.core.Script.eval(Script.java:428) ~[commandhelper-3.3.5-SNAPSHOT-full.jar:?]
	at com.laytonsmith.core.MethodScriptCompiler.execute(MethodScriptCompiler.java:2828) ~[commandhelper-3.3.5-SNAPSHOT-full.jar:?]
	at com.laytonsmith.core.MethodScriptCompiler.execute(MethodScriptCompiler.java:2786) ~[commandhelper-3.3.5-SNAPSHOT-full.jar:?]
	at com.laytonsmith.core.Script.run(Script.java:253) ~[commandhelper-3.3.5-SNAPSHOT-full.jar:?]
	at com.laytonsmith.core.AliasCore.alias(AliasCore.java:170) ~[commandhelper-3.3.5-SNAPSHOT-full.jar:?]
	at com.laytonsmith.commandhelper.CommandHelperServerListener.onServerCommand(CommandHelperServerListener.java:48) ~[commandhelper-3.3.5-SNAPSHOT-full.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor48.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-250]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:505) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-250]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-250]
	... 1 more
[07:20:09] [DiscordConnect/INFO]: [net.dv8tion.jda.api.JDA] Login Successful!
[07:20:09] [JDA MainWS-ReadThread/INFO]: [net.dv8tion.jda.internal.requests.WebSocketClient] Connected to WebSocket
[07:20:09] [JDA MainWS-ReadThread/INFO]: [net.dv8tion.jda.api.JDA] Finished Loading!
```

**Comment by PseudoKnight** [comment]
It's possible this is happening on startup too. Could just be the connection thread.

**Comment by PseudoKnight** [comment]
Updated to 5.0.0 alpha 9 here: 95c64ef8fe8a0ea9970b4fac93560c25487c9614

It hard-codes the gateway url, which will prevent this request from even happening at this point in the connection process. This should help with the reported error, but might not solve the underlying issue, which may be related to how I'm threading the connection process. But since it happened consistently with only one user, there could be some other condition like connection issues requiring retries or maybe how their scripts are setup.
